/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channels */
        get: operations["list_channels_api_v1_channels_get"];
        put?: never;
        /** Create Channel */
        post: operations["create_channel_api_v1_channels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel */
        get: operations["get_channel_api_v1_channels__channel_id__get"];
        put?: never;
        post?: never;
        /** Delete Channel */
        delete: operations["delete_channel_api_v1_channels__channel_id__delete"];
        options?: never;
        head?: never;
        /** Update Channel */
        patch: operations["update_channel_api_v1_channels__channel_id__patch"];
        trace?: never;
    };
    "/api/v1/channels/{channel_id}/sync-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Metrics */
        post: operations["sync_metrics_api_v1_channels__channel_id__sync_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["list_topics_api_v1_topics_get"];
        put?: never;
        /** Create Topic */
        post: operations["create_topic_api_v1_topics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/status-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic Status Summary */
        get: operations["topic_status_summary_api_v1_topics_status_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic */
        get: operations["get_topic_api_v1_topics__topic_id__get"];
        put?: never;
        post?: never;
        /** Delete Topic */
        delete: operations["delete_topic_api_v1_topics__topic_id__delete"];
        options?: never;
        head?: never;
        /** Update Topic */
        patch: operations["update_topic_api_v1_topics__topic_id__patch"];
        trace?: never;
    };
    "/api/v1/briefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Briefs */
        get: operations["list_briefs_api_v1_briefs_get"];
        put?: never;
        /** Create Brief */
        post: operations["create_brief_api_v1_briefs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/briefs/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Brief */
        post: operations["generate_brief_api_v1_briefs_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/briefs/{brief_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brief */
        get: operations["get_brief_api_v1_briefs__brief_id__get"];
        put?: never;
        post?: never;
        /** Delete Brief */
        delete: operations["delete_brief_api_v1_briefs__brief_id__delete"];
        options?: never;
        head?: never;
        /** Update Brief */
        patch: operations["update_brief_api_v1_briefs__brief_id__patch"];
        trace?: never;
    };
    "/api/v1/scripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scripts */
        get: operations["list_scripts_api_v1_scripts_get"];
        put?: never;
        /** Create Script */
        post: operations["create_script_api_v1_scripts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scripts/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Script */
        post: operations["generate_script_api_v1_scripts_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scripts/{script_id}/generate-audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Script Audio */
        post: operations["generate_script_audio_api_v1_scripts__script_id__generate_audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scripts/{script_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Script */
        get: operations["get_script_api_v1_scripts__script_id__get"];
        put?: never;
        post?: never;
        /** Delete Script */
        delete: operations["delete_script_api_v1_scripts__script_id__delete"];
        options?: never;
        head?: never;
        /** Update Script */
        patch: operations["update_script_api_v1_scripts__script_id__patch"];
        trace?: never;
    };
    "/api/v1/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Publications */
        get: operations["list_publications_api_v1_publications_get"];
        put?: never;
        /** Create Publication */
        post: operations["create_publication_api_v1_publications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publications/{publication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Publication */
        get: operations["get_publication_api_v1_publications__publication_id__get"];
        put?: never;
        post?: never;
        /** Delete Publication */
        delete: operations["delete_publication_api_v1_publications__publication_id__delete"];
        options?: never;
        head?: never;
        /** Update Publication */
        patch: operations["update_publication_api_v1_publications__publication_id__patch"];
        trace?: never;
    };
    "/api/v1/publications/{publication_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_v1_publications__publication_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/publications/{publication_id}/publish-pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Pipeline */
        post: operations["publish_pipeline_api_v1_publications__publication_id__publish_pipeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflows */
        get: operations["list_workflows_api_v1_workflows_get"];
        put?: never;
        /**
         * Trigger Workflow
         * @description Create a new workflow run and dispatch it to the worker.
         */
        post: operations["trigger_workflow_api_v1_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow */
        get: operations["get_workflow_api_v1_workflows__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{run_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Trail */
        get: operations["get_audit_trail_api_v1_workflows__run_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{run_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Context */
        patch: operations["patch_context_api_v1_workflows__run_id__context_patch"];
        trace?: never;
    };
    "/api/v1/workflows/{run_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Workflow */
        post: operations["pause_workflow_api_v1_workflows__run_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Workflow */
        post: operations["resume_workflow_api_v1_workflows__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Workflow */
        post: operations["cancel_workflow_api_v1_workflows__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Workflow */
        post: operations["retry_workflow_api_v1_workflows__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{run_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_workflows__run_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{run_id}/jobs/{step_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_workflows__run_id__jobs__step_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{run_id}/jobs/{step_id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip Job */
        post: operations["skip_job_api_v1_workflows__run_id__jobs__step_id__skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{run_id}/jobs/{step_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_v1_workflows__run_id__jobs__step_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{run_id}/jobs/{step_id}/inject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject Result
         * @description Manually mark a job as completed with a provided output dict.
         *     Use this to bypass a failing step when you have the result already.
         */
        post: operations["inject_result_api_v1_workflows__run_id__jobs__step_id__inject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BriefCreate */
        BriefCreate: {
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Topic Id */
            topic_id?: string | null;
            /** Title */
            title: string;
            /**
             * Target Audience
             * @default
             */
            target_audience: string;
            /** Key Points */
            key_points?: string[];
            /** Seo Keywords */
            seo_keywords?: string[];
            /** Competitor Urls */
            competitor_urls?: string[];
            /**
             * Estimated Duration Seconds
             * @default 600
             */
            estimated_duration_seconds: number;
            /**
             * Tone
             * @default educational
             */
            tone: string;
            /** Notes */
            notes?: string | null;
        };
        /** BriefGenerateRequest */
        BriefGenerateRequest: {
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
            /** Additional Instructions */
            additional_instructions?: string | null;
        };
        /** BriefRead */
        BriefRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Topic Id */
            topic_id: string | null;
            /** Title */
            title: string;
            /** Target Audience */
            target_audience: string;
            /** Key Points */
            key_points: string[];
            /** Seo Keywords */
            seo_keywords: string[];
            /** Competitor Urls */
            competitor_urls: string[];
            /** Estimated Duration Seconds */
            estimated_duration_seconds: number;
            /** Tone */
            tone: string;
            /** Status */
            status: string;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BriefUpdate */
        BriefUpdate: {
            /** Title */
            title?: string | null;
            /** Target Audience */
            target_audience?: string | null;
            /** Key Points */
            key_points?: string[] | null;
            /** Seo Keywords */
            seo_keywords?: string[] | null;
            /** Competitor Urls */
            competitor_urls?: string[] | null;
            /** Estimated Duration Seconds */
            estimated_duration_seconds?: number | null;
            /** Tone */
            tone?: string | null;
            /** Status */
            status?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ChannelCreate */
        ChannelCreate: {
            /** Name */
            name: string;
            /** Niche */
            niche: string;
            /** Handle */
            handle?: string | null;
        };
        /** ChannelRead */
        ChannelRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Youtube Channel Id */
            youtube_channel_id: string | null;
            /** Name */
            name: string;
            /** Handle */
            handle: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Niche */
            niche: string;
            /** Status */
            status: string;
            /** Subscriber Count */
            subscriber_count: number;
            /** View Count */
            view_count: number;
            /** Video Count */
            video_count: number;
            /** Monetization Enabled */
            monetization_enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ChannelUpdate */
        ChannelUpdate: {
            /** Name */
            name?: string | null;
            /** Niche */
            niche?: string | null;
            /** Handle */
            handle?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InjectResultRequest
         * @description Body for POST /workflows/{run_id}/jobs/{job_id}/inject.
         */
        InjectResultRequest: {
            /**
             * Output
             * @description Output dict to inject as job result
             */
            output: {
                [key: string]: unknown;
            };
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "scheduled" | "running" | "completed" | "failed" | "retrying" | "skipped" | "cancelled";
        /**
         * OverrideContextRequest
         * @description Body for PATCH /workflows/{run_id}/context.
         */
        OverrideContextRequest: {
            /**
             * Updates
             * @description Keys to merge into the run context
             */
            updates: {
                [key: string]: unknown;
            };
        };
        /** PaginatedResponse[BriefRead] */
        PaginatedResponse_BriefRead_: {
            /** Items */
            items: components["schemas"]["BriefRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Has Next */
            has_next: boolean;
            /** Has Prev */
            has_prev: boolean;
        };
        /** PaginatedResponse[ChannelRead] */
        PaginatedResponse_ChannelRead_: {
            /** Items */
            items: components["schemas"]["ChannelRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Has Next */
            has_next: boolean;
            /** Has Prev */
            has_prev: boolean;
        };
        /** PaginatedResponse[PublicationRead] */
        PaginatedResponse_PublicationRead_: {
            /** Items */
            items: components["schemas"]["PublicationRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Has Next */
            has_next: boolean;
            /** Has Prev */
            has_prev: boolean;
        };
        /** PaginatedResponse[ScriptRead] */
        PaginatedResponse_ScriptRead_: {
            /** Items */
            items: components["schemas"]["ScriptRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Has Next */
            has_next: boolean;
            /** Has Prev */
            has_prev: boolean;
        };
        /** PaginatedResponse[TopicRead] */
        PaginatedResponse_TopicRead_: {
            /** Items */
            items: components["schemas"]["TopicRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Has Next */
            has_next: boolean;
            /** Has Prev */
            has_prev: boolean;
        };
        /** PublicationCreate */
        PublicationCreate: {
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Script Id */
            script_id?: string | null;
            /** Brief Id */
            brief_id?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Visibility
             * @default private
             */
            visibility: string;
            /** Scheduled At */
            scheduled_at?: string | null;
        };
        /** PublicationRead */
        PublicationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Script Id */
            script_id: string | null;
            /** Brief Id */
            brief_id: string | null;
            /** Youtube Video Id */
            youtube_video_id: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Tags */
            tags: string[];
            /** Status */
            status: string;
            /** Visibility */
            visibility: string;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Scheduled At */
            scheduled_at: string | null;
            /** Published At */
            published_at: string | null;
            /** View Count */
            view_count: number;
            /** Like Count */
            like_count: number;
            /** Comment Count */
            comment_count: number;
            /** Revenue Usd */
            revenue_usd: number;
            /** Last Error */
            last_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PublicationUpdate */
        PublicationUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Visibility */
            visibility?: string | null;
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Status */
            status?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
        };
        /** PublishPipelineRequest */
        PublishPipelineRequest: {
            /** Media Url */
            media_url: string;
            /** Audio Url */
            audio_url?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Visibility */
            visibility?: string | null;
        };
        /**
         * RetryRequest
         * @description Body for POST /workflows/{run_id}/retry.
         */
        RetryRequest: {
            /**
             * Reset Context
             * @description If true, reset context to the original run input before retrying
             * @default false
             */
            reset_context: boolean;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "paused" | "completed" | "failed" | "cancelled";
        /** ScriptAudioGenerateRequest */
        ScriptAudioGenerateRequest: {
            /**
             * Voice Id
             * @default alloy
             */
            voice_id: string;
            /**
             * Provider
             * @default openai
             */
            provider: string;
            /**
             * Tempo
             * @default 1
             */
            tempo: number;
            /**
             * Tone
             * @default 0
             */
            tone: number;
        };
        /** ScriptCreate */
        ScriptCreate: {
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Title */
            title: string;
            /**
             * Hook
             * @default
             */
            hook: string;
            /**
             * Body
             * @default
             */
            body: string;
            /**
             * Cta
             * @default
             */
            cta: string;
            /** Keywords */
            keywords?: string[];
            /**
             * Target Duration Seconds
             * @default 600
             */
            target_duration_seconds: number;
            /**
             * Tone
             * @default educational
             */
            tone: string;
        };
        /** ScriptGenerateRequest */
        ScriptGenerateRequest: {
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Topic */
            topic: string;
            /**
             * Tone
             * @default educational
             */
            tone: string;
            /**
             * Target Duration Seconds
             * @default 600
             */
            target_duration_seconds: number;
            /** Keywords */
            keywords?: string[];
            /** Additional Context */
            additional_context?: string | null;
        };
        /** ScriptRead */
        ScriptRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Title */
            title: string;
            /** Hook */
            hook: string;
            /** Body */
            body: string;
            /** Cta */
            cta: string;
            /** Keywords */
            keywords: string[];
            /** Target Duration Seconds */
            target_duration_seconds: number;
            /** Tone */
            tone: string;
            /** Status */
            status: string;
            /** Seo Score */
            seo_score: number | null;
            /** Compliance Score */
            compliance_score: number | null;
            /** Version */
            version: number;
            /** Audio Url */
            audio_url: string | null;
            /** Audio Duration Seconds */
            audio_duration_seconds: number | null;
            /** Audio Provider */
            audio_provider: string | null;
            /** Audio Voice Id */
            audio_voice_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScriptUpdate */
        ScriptUpdate: {
            /** Title */
            title?: string | null;
            /** Hook */
            hook?: string | null;
            /** Body */
            body?: string | null;
            /** Cta */
            cta?: string | null;
            /** Keywords */
            keywords?: string[] | null;
            /** Status */
            status?: string | null;
        };
        /** TaskResponse */
        TaskResponse: {
            /** Task Id */
            task_id: string;
            /** Status */
            status: string;
        };
        /** TopicCreate */
        TopicCreate: {
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Keywords */
            keywords?: string[];
            /**
             * Source
             * @default manual
             */
            source: string;
        };
        /** TopicRead */
        TopicRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Keywords */
            keywords: string[];
            /** Trend Score */
            trend_score: number | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Research Notes */
            research_notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TopicStatusCount */
        TopicStatusCount: {
            /**
             * New
             * @default 0
             */
            new: number;
            /**
             * Researching
             * @default 0
             */
            researching: number;
            /**
             * Briefed
             * @default 0
             */
            briefed: number;
            /**
             * Rejected
             * @default 0
             */
            rejected: number;
            /**
             * Archived
             * @default 0
             */
            archived: number;
        };
        /** TopicUpdate */
        TopicUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Keywords */
            keywords?: string[] | null;
            /** Status */
            status?: string | null;
            /** Trend Score */
            trend_score?: number | null;
            /** Research Notes */
            research_notes?: string | null;
        };
        /**
         * TriggerRequest
         * @description Body for POST /workflows — create and start a run.
         */
        TriggerRequest: {
            /**
             * Pipeline Name
             * @default youtube_content
             */
            pipeline_name: string;
            /** Channel Id */
            channel_id?: string | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkflowActionResponse
         * @description Generic response for action endpoints.
         */
        WorkflowActionResponse: {
            /** Status */
            status: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Message
             * @default
             */
            message: string;
            /** Task Id */
            task_id?: string | null;
        };
        /** WorkflowAuditEventRead */
        WorkflowAuditEventRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Job Id */
            job_id: string | null;
            /** Event Type */
            event_type: string;
            /** Actor */
            actor: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** WorkflowAuditResponse */
        WorkflowAuditResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Events */
            events: components["schemas"]["WorkflowAuditEventRead"][];
            /** Total */
            total: number;
        };
        /** WorkflowJobRead */
        WorkflowJobRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Step Id */
            step_id: string;
            /** Step Type */
            step_type: string;
            status: components["schemas"]["JobStatus"];
            /** Attempt */
            attempt: number;
            /** Max Attempts */
            max_attempts: number;
            /** Celery Task Id */
            celery_task_id: string | null;
            /** Output */
            output: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /** Is Manual Result */
            is_manual_result: boolean;
            /** Manual Actor */
            manual_actor: string | null;
            /** Attempt History */
            attempt_history: {
                [key: string]: unknown;
            }[];
            /** Scheduled At */
            scheduled_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Retry After */
            retry_after: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WorkflowListResponse */
        WorkflowListResponse: {
            /** Items */
            items: components["schemas"]["WorkflowRunSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Has Next */
            has_next: boolean;
            /** Has Prev */
            has_prev: boolean;
        };
        /** WorkflowRunRead */
        WorkflowRunRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Channel Id */
            channel_id: string | null;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Pipeline Name */
            pipeline_name: string;
            /** Pipeline Version */
            pipeline_version: string;
            status: components["schemas"]["RunStatus"];
            /** Triggered By */
            triggered_by: string;
            /** Context */
            context: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Paused At */
            paused_at: string | null;
            /** Parent Run Id */
            parent_run_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Jobs */
            jobs?: components["schemas"]["WorkflowJobRead"][];
        };
        /**
         * WorkflowRunSummary
         * @description Lightweight list-view — no jobs embedded.
         */
        WorkflowRunSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Channel Id */
            channel_id: string | null;
            /** Pipeline Name */
            pipeline_name: string;
            /** Pipeline Version */
            pipeline_version: string;
            status: components["schemas"]["RunStatus"];
            /** Triggered By */
            triggered_by: string;
            /** Error */
            error: string | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Paused At */
            paused_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_channels_api_v1_channels_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ChannelRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_channel_api_v1_channels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_channel_api_v1_channels__channel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_channel_api_v1_channels__channel_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_channel_api_v1_channels__channel_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_metrics_api_v1_channels__channel_id__sync_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_api_v1_topics_get: {
        parameters: {
            query?: {
                channel_id?: string | null;
                status?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_TopicRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_topic_api_v1_topics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topic_status_summary_api_v1_topics_status_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicStatusCount"];
                };
            };
        };
    };
    get_topic_api_v1_topics__topic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_topic_api_v1_topics__topic_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_topic_api_v1_topics__topic_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_briefs_api_v1_briefs_get: {
        parameters: {
            query?: {
                channel_id?: string | null;
                topic_id?: string | null;
                status?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_BriefRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_brief_api_v1_briefs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_brief_api_v1_briefs_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brief_api_v1_briefs__brief_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_brief_api_v1_briefs__brief_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_brief_api_v1_briefs__brief_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brief_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scripts_api_v1_scripts_get: {
        parameters: {
            query?: {
                channel_id?: string | null;
                brief_id?: string | null;
                status?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ScriptRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_script_api_v1_scripts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_script_api_v1_scripts_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_script_audio_api_v1_scripts__script_id__generate_audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                script_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptAudioGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_script_api_v1_scripts__script_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                script_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_script_api_v1_scripts__script_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                script_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_script_api_v1_scripts__script_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                script_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScriptRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_publications_api_v1_publications_get: {
        parameters: {
            query?: {
                channel_id?: string | null;
                status?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_PublicationRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_publication_api_v1_publications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_publication_api_v1_publications__publication_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_publication_api_v1_publications__publication_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_publication_api_v1_publications__publication_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v1_publications__publication_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_pipeline_api_v1_publications__publication_id__publish_pipeline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publication_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishPipelineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflows_api_v1_workflows_get: {
        parameters: {
            query?: {
                channel_id?: string | null;
                pipeline_name?: string | null;
                status?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_workflow_api_v1_workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_api_v1_workflows__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_trail_api_v1_workflows__run_id__audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowAuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_context_api_v1_workflows__run_id__context_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideContextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_workflow_api_v1_workflows__run_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_workflow_api_v1_workflows__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_workflow_api_v1_workflows__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_workflow_api_v1_workflows__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_workflows__run_id__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJobRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_workflows__run_id__jobs__step_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_job_api_v1_workflows__run_id__jobs__step_id__skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_v1_workflows__run_id__jobs__step_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inject_result_api_v1_workflows__run_id__jobs__step_id__inject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectResultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
